import 'package:flutter/material.dart';

class FoodInfo {
  final String name;
  final String serving;
  final String description;
  final Map<String, String> nutrition;
  final List<String> benefits;
  final IconData icon;
  final Color accent;

  const FoodInfo({
    required this.name,
    required this.serving,
    required this.description,
    required this.nutrition,
    required this.benefits,
    required this.icon,
    required this.accent,
  });
}

class FoodInfoService {
  static final Map<String, FoodInfo> _foods = {
    'Eggs': const FoodInfo(
      name: 'Eggs',
      serving: '1 large egg',
      description: 'Eggs provide high-quality protein along with key vitamins and minerals in a compact serving.',
      nutrition: {'Calories': '72 kcal', 'Protein': '6.3 g', 'Fat': '4.8 g', 'Carbs': '0.4 g'},
      benefits: ['Supports muscle repair', 'Provides choline', 'Easy breakfast protein'],
      icon: Icons.egg_alt,
      accent: Color(0xFFE9B949),
    ),
    'Chicken': const FoodInfo(
      name: 'Chicken',
      serving: '100 g cooked breast',
      description: 'Chicken breast is a lean protein source often used for balanced meals and recovery-focused eating.',
      nutrition: {'Calories': '165 kcal', 'Protein': '31 g', 'Fat': '3.6 g', 'Carbs': '0 g'},
      benefits: ['Lean protein', 'Helps fullness', 'Works well in meal prep'],
      icon: Icons.set_meal,
      accent: Color(0xFFD97B66),
    ),
    'Lentils': const FoodInfo(
      name: 'Lentils',
      serving: '1 cup cooked',
      description: 'Lentils are rich in plant protein, fiber, and minerals like iron, making them a strong everyday staple.',
      nutrition: {'Calories': '230 kcal', 'Protein': '18 g', 'Fiber': '15.6 g', 'Iron': '6.6 mg'},
      benefits: ['Plant protein', 'High fiber', 'Supports iron intake'],
      icon: Icons.grain,
      accent: Color(0xFF8E6C4D),
    ),
    'Greek yogurt': const FoodInfo(
      name: 'Greek yogurt',
      serving: '170 g plain',
      description: 'Greek yogurt offers dense protein, calcium, and a creamy texture with less sugar when unsweetened.',
      nutrition: {'Calories': '100 kcal', 'Protein': '17 g', 'Calcium': '187 mg', 'Fat': '0.7 g'},
      benefits: ['High protein snack', 'Supports bone health', 'Pairs well with fruit'],
      icon: Icons.icecream,
      accent: Color(0xFF7DA8D6),
    ),
    'Tofu': const FoodInfo(
      name: 'Tofu',
      serving: '100 g firm tofu',
      description: 'Tofu is a versatile soy food that provides protein and, when fortified, can also add calcium.',
      nutrition: {'Calories': '144 kcal', 'Protein': '17 g', 'Fat': '9 g', 'Calcium': '350 mg'},
      benefits: ['Plant-based protein', 'Versatile in meals', 'Can support calcium goals'],
      icon: Icons.crop_square,
      accent: Color(0xFF8FC39A),
    ),
    'Lean beef': const FoodInfo(
      name: 'Lean beef',
      serving: '85 g cooked',
      description: 'Lean beef is a concentrated source of protein, iron, zinc, and vitamin B12.',
      nutrition: {'Calories': '170 kcal', 'Protein': '25 g', 'Iron': '2.1 mg', 'Zinc': '4.8 mg'},
      benefits: ['Iron-rich', 'Supports protein needs', 'Contains vitamin B12'],
      icon: Icons.lunch_dining,
      accent: Color(0xFFB8625C),
    ),
    'Spinach': const FoodInfo(
      name: 'Spinach',
      serving: '1 cup cooked',
      description: 'Spinach adds folate, vitamin K, and non-heme iron, especially when paired with vitamin C foods.',
      nutrition: {'Calories': '41 kcal', 'Iron': '6.4 mg', 'Vitamin A': '943 mcg', 'Fiber': '4.3 g'},
      benefits: ['Iron support', 'Vitamin A source', 'Easy in curries and salads'],
      icon: Icons.eco,
      accent: Color(0xFF4FA86E),
    ),
    'Beans': const FoodInfo(
      name: 'Beans',
      serving: '1 cup cooked',
      description: 'Beans provide slow-digesting carbohydrates, fiber, and plant-based protein.',
      nutrition: {'Calories': '245 kcal', 'Protein': '15 g', 'Fiber': '15 g', 'Iron': '4.5 mg'},
      benefits: ['Supports fullness', 'Plant protein', 'Good fiber source'],
      icon: Icons.spa,
      accent: Color(0xFF9B7048),
    ),
    'Fortified cereal': const FoodInfo(
      name: 'Fortified cereal',
      serving: '1 serving',
      description: 'Fortified cereals can help fill nutrient gaps, especially for iron and vitamin D.',
      nutrition: {'Calories': '110 kcal', 'Iron': '18 mg', 'Vitamin D': '2.5 mcg', 'Carbs': '24 g'},
      benefits: ['Convenient breakfast', 'Often iron-fortified', 'Useful for vitamin D support'],
      icon: Icons.breakfast_dining,
      accent: Color(0xFFD1A84A),
    ),
    'Milk': const FoodInfo(
      name: 'Milk',
      serving: '1 cup',
      description: 'Milk is a classic source of calcium, protein, and, when fortified, vitamin D.',
      nutrition: {'Calories': '122 kcal', 'Protein': '8 g', 'Calcium': '306 mg', 'Vitamin D': '2.9 mcg'},
      benefits: ['Bone support', 'Adds protein', 'Pairs easily with meals'],
      icon: Icons.local_drink,
      accent: Color(0xFF81B5E1),
    ),
    'Yogurt': const FoodInfo(
      name: 'Yogurt',
      serving: '1 cup plain',
      description: 'Yogurt provides calcium and protein and can be a practical snack or breakfast base.',
      nutrition: {'Calories': '149 kcal', 'Protein': '8.5 g', 'Calcium': '296 mg', 'Fat': '8 g'},
      benefits: ['Bone support', 'Easy snack option', 'Can support protein intake'],
      icon: Icons.icecream_outlined,
      accent: Color(0xFF91B8E4),
    ),
    'Cheese': const FoodInfo(
      name: 'Cheese',
      serving: '30 g',
      description: 'Cheese contains calcium and protein in a concentrated form, though portions matter.',
      nutrition: {'Calories': '120 kcal', 'Protein': '7 g', 'Calcium': '200 mg', 'Fat': '10 g'},
      benefits: ['High calcium', 'Convenient topping', 'Pairs with snacks and meals'],
      icon: Icons.check_box_outline_blank,
      accent: Color(0xFFF0C35A),
    ),
    'Sardines': const FoodInfo(
      name: 'Sardines',
      serving: '85 g canned',
      description: 'Sardines are rich in calcium, vitamin D, omega-3 fats, and protein.',
      nutrition: {'Calories': '191 kcal', 'Protein': '22 g', 'Calcium': '325 mg', 'Vitamin D': '4.8 mcg'},
      benefits: ['Bone-support nutrients', 'Omega-3 fats', 'Good protein source'],
      icon: Icons.phishing,
      accent: Color(0xFF5F90B7),
    ),
    'Bananas': const FoodInfo(
      name: 'Bananas',
      serving: '1 medium banana',
      description: 'Bananas add potassium and carbohydrates that fit well into snacks or pre-workout meals.',
      nutrition: {'Calories': '105 kcal', 'Potassium': '422 mg', 'Carbs': '27 g', 'Fiber': '3.1 g'},
      benefits: ['Potassium source', 'Portable snack', 'Quick energy'],
      icon: Icons.ramen_dining,
      accent: Color(0xFFE4C94B),
    ),
    'Potatoes': const FoodInfo(
      name: 'Potatoes',
      serving: '1 medium baked',
      description: 'Potatoes provide potassium and carbohydrates, especially when eaten with the skin.',
      nutrition: {'Calories': '161 kcal', 'Potassium': '926 mg', 'Carbs': '37 g', 'Fiber': '3.8 g'},
      benefits: ['High potassium', 'Budget friendly', 'Works in many meals'],
      icon: Icons.circle,
      accent: Color(0xFFC59E69),
    ),
    'Tomatoes': const FoodInfo(
      name: 'Tomatoes',
      serving: '1 cup chopped',
      description: 'Tomatoes contribute potassium and vitamin C with very few calories.',
      nutrition: {'Calories': '32 kcal', 'Potassium': '427 mg', 'Vitamin C': '24 mg', 'Water': '95%'},
      benefits: ['Hydrating', 'Adds vitamin C', 'Easy in salads and curries'],
      icon: Icons.apple,
      accent: Color(0xFFE16B5A),
    ),
    'Sweet potato': const FoodInfo(
      name: 'Sweet potato',
      serving: '1 medium baked',
      description: 'Sweet potatoes are especially rich in vitamin A and also bring fiber and potassium.',
      nutrition: {'Calories': '112 kcal', 'Vitamin A': '1096 mcg', 'Fiber': '3.9 g', 'Potassium': '438 mg'},
      benefits: ['Vitamin A rich', 'Comforting complex carb', 'Good for meal bowls'],
      icon: Icons.circle_outlined,
      accent: Color(0xFFD98947),
    ),
    'Carrots': const FoodInfo(
      name: 'Carrots',
      serving: '1 cup chopped',
      description: 'Carrots are known for beta-carotene, which the body converts into vitamin A.',
      nutrition: {'Calories': '52 kcal', 'Vitamin A': '1069 mcg', 'Fiber': '3.6 g', 'Carbs': '12 g'},
      benefits: ['Vision-support nutrient', 'Crunchy snack', 'Easy to add to meals'],
      icon: Icons.spa_outlined,
      accent: Color(0xFFF08A3A),
    ),
    'Fortified milk': const FoodInfo(
      name: 'Fortified milk',
      serving: '1 cup',
      description: 'Fortified milk can add calcium and vitamin D together in one serving.',
      nutrition: {'Calories': '122 kcal', 'Protein': '8 g', 'Calcium': '306 mg', 'Vitamin D': '2.9 mcg'},
      benefits: ['Bone support', 'Vitamin D source', 'Easy with breakfast'],
      icon: Icons.local_drink_outlined,
      accent: Color(0xFF88B9E3),
    ),
    'Guava': const FoodInfo(
      name: 'Guava',
      serving: '1 cup',
      description: 'Guava is an exceptionally vitamin C-rich fruit with fiber and a refreshing taste.',
      nutrition: {'Calories': '112 kcal', 'Vitamin C': '377 mg', 'Fiber': '9 g', 'Carbs': '24 g'},
      benefits: ['Very high vitamin C', 'Fiber-rich fruit', 'Supports iron absorption'],
      icon: Icons.apple_outlined,
      accent: Color(0xFF7CCB8A),
    ),
    'Oranges': const FoodInfo(
      name: 'Oranges',
      serving: '1 medium orange',
      description: 'Oranges are a familiar source of vitamin C and fluid, making them useful for hydration support too.',
      nutrition: {'Calories': '62 kcal', 'Vitamin C': '70 mg', 'Fiber': '3.1 g', 'Water': '87%'},
      benefits: ['Vitamin C source', 'Hydrating fruit', 'Supports iron absorption'],
      icon: Icons.circle,
      accent: Color(0xFFF39B34),
    ),
    'Strawberries': const FoodInfo(
      name: 'Strawberries',
      serving: '1 cup halves',
      description: 'Strawberries add vitamin C, antioxidants, and natural sweetness with relatively low calories.',
      nutrition: {'Calories': '49 kcal', 'Vitamin C': '89 mg', 'Fiber': '3 g', 'Water': '91%'},
      benefits: ['Vitamin C rich', 'Hydrating', 'Works in snacks and yogurt bowls'],
      icon: Icons.local_florist,
      accent: Color(0xFFE26478),
    ),
    'Bell peppers': const FoodInfo(
      name: 'Bell peppers',
      serving: '1 cup chopped',
      description: 'Bell peppers are one of the strongest vegetable sources of vitamin C and add crunch to meals.',
      nutrition: {'Calories': '39 kcal', 'Vitamin C': '190 mg', 'Fiber': '3.1 g', 'Vitamin A': '117 mcg'},
      benefits: ['Very high vitamin C', 'Colorful meal addition', 'Low-calorie vegetable'],
      icon: Icons.emoji_food_beverage,
      accent: Color(0xFFE0504D),
    ),
    'Broccoli': const FoodInfo(
      name: 'Broccoli',
      serving: '1 cup cooked',
      description: 'Broccoli contributes vitamin C, fiber, and useful plant compounds in a filling vegetable serving.',
      nutrition: {'Calories': '55 kcal', 'Vitamin C': '102 mg', 'Fiber': '5.1 g', 'Protein': '3.7 g'},
      benefits: ['Vitamin C rich', 'High fiber vegetable', 'Pairs well with main meals'],
      icon: Icons.park,
      accent: Color(0xFF4CA86C),
    ),
    'Salmon': const FoodInfo(
      name: 'Salmon',
      serving: '100 g cooked',
      description: 'Salmon is known for protein, vitamin D, and omega-3 fats that support overall health.',
      nutrition: {'Calories': '206 kcal', 'Protein': '22 g', 'Vitamin D': '10 mcg', 'Fat': '12 g'},
      benefits: ['Vitamin D source', 'Omega-3 fats', 'Strong protein option'],
      icon: Icons.set_meal_outlined,
      accent: Color(0xFFDE7A63),
    ),
    'Egg yolks': const FoodInfo(
      name: 'Egg yolks',
      serving: '1 yolk',
      description: 'Egg yolks contain vitamin D, choline, and fat-soluble nutrients in a small serving.',
      nutrition: {'Calories': '55 kcal', 'Protein': '2.7 g', 'Vitamin D': '1 mcg', 'Fat': '4.5 g'},
      benefits: ['Vitamin D support', 'Contains choline', 'Adds richness to meals'],
      icon: Icons.egg,
      accent: Color(0xFFF0BE4A),
    ),
    'Water': const FoodInfo(
      name: 'Water',
      serving: '1 cup (240 ml)',
      description: 'Plain water is the simplest way to meet hydration goals without adding calories or sugar.',
      nutrition: {'Calories': '0 kcal', 'Water': '100%'},
      benefits: ['Zero calorie hydration', 'Supports digestion and temperature regulation', 'Easy to track by the cup'],
      icon: Icons.opacity,
      accent: Color(0xFF5AA6E8),
    ),
    'Watermelon': const FoodInfo(
      name: 'Watermelon',
      serving: '1 cup diced',
      description: 'Watermelon is a hydrating fruit with natural sweetness and a very high water content.',
      nutrition: {'Calories': '46 kcal', 'Water': '92%', 'Vitamin C': '12 mg', 'Carbs': '11 g'},
      benefits: ['Hydration support', 'Refreshing snack', 'Light fruit option'],
      icon: Icons.water_drop,
      accent: Color(0xFFEE6D7A),
    ),
    'Cucumber': const FoodInfo(
      name: 'Cucumber',
      serving: '1 cup slices',
      description: 'Cucumber is very water-dense and useful for adding volume and freshness to meals.',
      nutrition: {'Calories': '16 kcal', 'Water': '95%', 'Vitamin K': '10 mcg', 'Carbs': '3.8 g'},
      benefits: ['Hydrating vegetable', 'Low calorie', 'Easy in salads and snacks'],
      icon: Icons.eco_outlined,
      accent: Color(0xFF76C48B),
    ),
    'Lettuce': const FoodInfo(
      name: 'Lettuce',
      serving: '1 cup shredded',
      description: 'Lettuce adds crunch and hydration with very few calories.',
      nutrition: {'Calories': '8 kcal', 'Water': '95%', 'Vitamin A': '205 mcg', 'Fiber': '0.8 g'},
      benefits: ['Hydrating base', 'Very low calorie', 'Pairs with many meals'],
      icon: Icons.grass,
      accent: Color(0xFF7BBC68),
    ),
    'Coconut water': const FoodInfo(
      name: 'Coconut water',
      serving: '1 cup',
      description: 'Coconut water is a beverage that contributes fluid and some potassium.',
      nutrition: {'Calories': '46 kcal', 'Potassium': '600 mg', 'Carbs': '9 g', 'Water': '95%'},
      benefits: ['Fluid support', 'Contains potassium', 'Refreshing drink option'],
      icon: Icons.sports_bar,
      accent: Color(0xFF8DBA8A),
    ),
  };

  static FoodInfo getFood(String name) {
    return _foods[name] ??
        FoodInfo(
          name: name,
          serving: '1 serving',
          description: '$name can be part of a balanced eating plan depending on portion size and preparation.',
          nutrition: const {
            'Calories': 'Varies',
            'Protein': 'Varies',
            'Carbs': 'Varies',
            'Fat': 'Varies',
          },
          benefits: const [
            'Can support meal variety',
            'Best used in balanced portions',
            'Nutrition depends on preparation',
          ],
          icon: Icons.restaurant_menu,
          accent: const Color(0xFF1563A7),
        );
  }
}

